WTTJ/welcome-ui

packages/Select/index.js

fix: not toggle menu on select disabled

---

docz/CodeEditor.styled.js
packages/Search/styles.js
scripts/edit-readme.js

fix: double cross on search

---

packages/Toggle/styles.js

fix: toggle animation on disabled

---

packages/DateTimePickerCommon/CustomPopper.js
packages/DateTimePickerCommon/package.json
packages/DropdownMenu/styles.js
packages/DropdownMenu/theme.js
packages/Search/styles.js
packages/Select/styles.js

feat: add cardStyle on component who need it

---

docz/CodeEditor.styled.js
packages/Button/styles.js
packages/Button/theme.js
packages/Core/utils/base.js
packages/Core/utils/reset.js
packages/DropdownMenu/Item.styled.js
packages/DropdownMenu/styles.js
packages/Link/index.js
packages/Modal/styled.js
packages/Pagination/styles.js
packages/Search/styles.js
packages/Select/styles.js
packages/Tabs/styles.js
packages/Toggle/styles.js
src/gatsby-theme-docz/components/Content.styled.js

fix: remove focus on firefox

---

packages/Core/index.test.js
packages/Core/theme/core.js

fix: createTheme correctly merges overriding styles

---

packages/Modal/index.js

fix: make Modal close when pressing Esc

---

docz/CodeEditor.styled.js
packages/DropdownMenu/doc.mdx
packages/DropdownMenu/index.js
packages/DropdownMenu/theme.js
src/gatsby-theme-docz/components/Navigation.styled.js
yarn.lock

chore: upgrade reakit and fix various warnings

---

packages/Core/theme/core.js
packages/Core/theme/dark.js
packages/Core/theme/typography.js
packages/Core/theme/welcome.js
packages/Core/theme/welcomekit.js
packages/InputText/styles.js
packages/Link/doc.mdx
packages/Link/index.js
packages/Link/theme.js
packages/Text/index.js
packages/UniversalLink/styles.js

refactor: separate default and hover styles on Link

---

packages/Hint/index.js
packages/Radio/index.js
packages/Radio/package.json
packages/Radio/styles.js
packages/RadioGroup/doc.mdx
packages/RadioGroup/index.js

feat: add hint on Radio

---

packages/Themes/Dark/README.md
packages/Themes/Dark/index.js
packages/Themes/Dark/package.json
packages/Themes/Dark/theme.js
packages/Themes/README.md
packages/Themes/Welcome/README.md
packages/Themes/Welcome/index.js
packages/Themes/Welcome/package.json
packages/Themes/Welcome/theme.js
packages/Themes/WelcomeKit/README.md
packages/Themes/WelcomeKit/index.js
packages/Themes/WelcomeKit/package.json
packages/Themes/WelcomeKit/theme.js
packages/Themes/Wttj/README.md
packages/Themes/Wttj/index.js
packages/Themes/Wttj/package.json
packages/Themes/Wttj/theme.js
packages/Themes/index.js
packages/Themes/package.json

Fixes #536 
First step, next step remove themes from Core component when this will be published.

feat: add themes packages

---

packages/Themes/Dark/package.json
packages/Themes/Dark/theme.js
packages/Themes/Welcome/package.json
packages/Themes/WelcomeKit/package.json
packages/Themes/WelcomeKit/theme.js
packages/Themes/Wttj/package.json
packages/Themes/package.json

fix(themes): imports

---

packages/Search/index.js

fix: search throttle persistence

---

src/gatsby-theme-docz/components/Content.styled.js
src/gatsby-theme-docz/index.js

fix: layout not wide enough

---

package.json
src/pages/404.js
yarn.lock

chore(docz): add 404 page

---

packages/Tabs/doc.mdx
packages/Tabs/index.js
packages/Tabs/index.test.js

fix: tabs component stopId deprecated

---

packages/Core/theme/colors.js
packages/Tag/doc.mdx
packages/Tag/index.test.js
packages/Tag/theme.js

refactor: change subcolor name

---

packages/IconFont/doc.mdx
src/gatsby-theme-docz/components/Content.styled.js
src/gatsby-theme-docz/components/MobileMenu.styled.js
src/gatsby-theme-docz/index.js

fix: remove useless height on layout

---

packages/Themes/Dark/README.md
packages/Themes/Welcome/README.md
packages/Themes/WelcomeKit/README.md
packages/Themes/Wttj/README.md

fix: fix typo in theme imports

---

packages/Breadcrumb/Item.js
packages/Breadcrumb/Item.styles.js
packages/Breadcrumb/README.md
packages/Breadcrumb/doc.mdx
packages/Breadcrumb/index.js
packages/Breadcrumb/index.test.js
packages/Breadcrumb/package.json
packages/Breadcrumb/styles.js
packages/Breadcrumb/theme.js
packages/Core/theme/core.js
src/index.js

feat: add Breadcrumb component

---

packages/Breadcrumb/index.js
packages/Breadcrumb/styles.js
packages/Breadcrumb/theme.js

feat(breadcrumb): add gradient on mobile

---

packages/Field/index.js
packages/Field/utils.js

https://www.loom.com/share/6831caef314f4a9d907b95140aae272f

fix: display errors on change for checkbox & radio

---

babel.config.js
package.json
yarn.lock

feat: add babel optional chaining

---

packages/Field/package.json
packages/Field/theme.js
packages/Search/styles.js
packages/Themes/Welcome/theme.js

also add a highlight + selected color

fix: welcome theme select highlight color was too light

---

packages/Search/index.js

fix: allow downshift props to be forwarded

---

src/gatsby-theme-docz/components/ThemeSelect.js
src/gatsby-theme-docz/index.js

fix: add welcome-home theme to docz

---

packages/Checkbox/doc.mdx
packages/Select/doc.mdx
packages/Select/index.js
packages/Select/styles.js
packages/Select/utils.js

https://www.loom.com/share/9a5fa1deed31413db67c0d329e32e98d

feat: add two new options on select to allow building search filters

---

packages/DatePicker/index.js
packages/DateTimePicker/index.js
packages/Loader/styles.js
packages/TimePicker/index.js

- Added missing property "disabled" on DateTimePicker
- Defined explicitly "disabled" property on DatePicker/TimePicker (visible on docs) 
- Fixed stylelint error into loader (thanks @guillaumewttj )

fix: missing disabled prop on DateTimePicker

---

packages/Alert/doc.mdx
packages/Alert/index.js
packages/Alert/styles.js
packages/Alert/theme.js

Feat new alerts

---

packages/Field/theme.js
packages/Label/index.test.js
packages/Label/styles.js
packages/VariantIcon/index.js
packages/VariantIcon/package.json
packages/VariantIcon/styles.js

feat: redesign label

---

packages/DropdownMenu/Item.styled.js

feat: redesign dropdown

---

docz/TagVersion.js
packages/Tag/doc.mdx
packages/Tag/index.test.js
packages/Tag/styles.js
packages/Tag/theme.js

feat: change Tags colors

---

packages/Accordion/theme.js

chore: accordion with new theme

---

packages/Pagination/index.js
packages/Pagination/package.json
packages/Pagination/styles.js
packages/Pagination/theme.js
packages/Themes/Welcome/theme.js

(j'ai hover sur le premier 10)

feat: redesign pagination

---

docz/Props.js
packages/Core/theme/core.js
packages/Table/styles.js
packages/Table/theme.js

feat(table): rebranding

---

packages/Core/theme/core.js
packages/Modal/doc.mdx
packages/Modal/index.js
packages/Modal/package.json
packages/Modal/styles.js
packages/Modal/theme.js
yarn.lock

https://www.loom.com/share/0cbbc84efc0f48fda002a7659e834dfe

feat(modal): rebranding and animation

---

docz/TagVersion.js
packages/Checkbox/index.js
packages/Core/theme/core.js
packages/Field/index.js
packages/Field/theme.js
packages/Label/index.js
packages/Toggle/doc.mdx
packages/Toggle/styles.js
packages/Toggle/theme.js

feat(toggle): rebranding

---

packages/Alert/index.js
packages/Alert/package.json
packages/Alert/styles.js
packages/ClearButton/index.js
packages/ClearButton/styles.js
packages/Hint/doc.mdx
packages/Hint/index.js
packages/Label/doc.mdx
packages/Label/index.js
packages/Label/index.test.js
packages/Toast/Growl.js
packages/Toast/Snackbar.js
packages/Toast/Title.js
packages/Toast/Title.test.js
packages/Toast/doc.mdx
packages/Toast/package.json
packages/Toast/styles.js
packages/Toast/theme.js
packages/Utils/variants.js
packages/VariantIcon/index.js
packages/VariantIcon/styles.js

Feat new toast

---

packages/Core/theme/core.js
packages/Core/theme/defaultFields.js
packages/DateTimePickerCommon/CustomHeader.js
packages/DateTimePickerCommon/CustomPopper.js
packages/DateTimePickerCommon/styles.js
packages/DateTimePickerCommon/theme.js
packages/Field/theme.js
packages/Search/styles.js
packages/Select/styles.js
packages/Themes/Welcome/theme.js

feat: redesign datepicker

---

packages/Core/theme/defaultFields.js
packages/MarkdownEditor/styles.js

feat: redesign MarkdownEditor

---

packages/Core/theme/colors.js
packages/Core/theme/core.js
packages/Core/theme/underline.js
packages/Link/doc.mdx
packages/Link/index.js
packages/Link/styles.js
packages/Link/theme.js
packages/Text/doc.mdx
packages/Text/index.js
packages/Text/styles.js

fix: link underline issue

---

packages/Link/index.js
packages/usage-refs.mdx

Signed-off-by: Guillaume Rousseau <guillaume.rousseau@wttj.co>

fix: link issue when children is an object

---

packages/Breadcrumb/Item.styles.js
packages/Breadcrumb/theme.js

fix: breadcrumb vertical alignment

---

packages/Core/theme/core.js
packages/Core/theme/typography.js
packages/Core/utils/base.js
packages/Link/index.js
packages/Text/doc.mdx
packages/Text/styles.js
packages/Themes/Welcome/theme.js

Signed-off-by: Théo Mesnil <theo.mesnil@wttj.co>

fix: move default letterSpacing and linHeight to welcome theme

---

packages/Icon/styles.js
packages/Loader/styles.js

Signed-off-by: Théo Mesnil <theo.mesnil@wttj.co>
Signed-off-by: François Robichet <francois.robichet@wttj.co>
Signed-off-by: Robert Douglas <robert@wttj.co>

fix: don't use useTheme in icons and loader styles

---

packages/Accordion/styles.js

fix: filterComponent not using array as second parameter

---

packages/Field/layout.js

fix(fields): change layout styled

---

packages/Field/layout.js

fix: revert #707 with new refacto and fix docz build

---

packages/Checkbox/styles.js
packages/Radio/index.js
packages/Radio/styles.js
packages/Radio/theme.js

- New icon for check state on Radio and Checkbox
- New style for a radio with an hint

feat: new check icon on Radio and add special style on Radio with hint

---

packages/Tabs/doc.mdx
packages/Tabs/index.js
packages/Tabs/styles.js
packages/Tabs/theme.js

feat: support of reakit orientation option on tabs

---

packages/Select/doc.mdx
packages/Select/index.js

fix: expose renderCreateItem on isCreatable Select

---

docs/package.json
docs/pages/_app.js
package.json
packages/DateTimePickerCommon/CustomPopper.js
packages/DateTimePickerCommon/datePickerStyles.js
packages/MarkdownEditor/easyMdeStyles.js
packages/MarkdownEditor/emojiMartStyles.js
packages/MarkdownEditor/styles.js
yarn.lock

fix: use styled-components css instead of css requires

---

docs/components/App.js
docs/components/Layout.js
docs/pages/getting-started.mdx
packages/Core/WuiProvider.js
packages/Core/utils/reset.js
packages/Utils/hide-focus-rings-root.js

feat: remove wrapping div added when using `shouldHideFocusRingOnClick`

---

README.md

The link is broken, and I think that's the correct new path. :tada:

Adjust link to illustration on README

---

.circleci/config.yml
package.json

fix: tests failing due to memory

---

.circleci/config.yml
package.json
yarn.lock

Feat docs cd

---

docs/pages/fields/markdown-editor.mdx
packages/MarkdownEditor/index.js
packages/MarkdownEditor/styles.js

feat(markdown-editor): add actions

---

docs/components/Code.js
docs/pages/fields/file-upload.mdx
packages/FileUpload/index.js

Add the possibility to put a custom Preview on FileUpload

feat(file-upload): add custom Preview

---

docs/components/App.js
docs/pages/getting-started.mdx
packages/Core/WuiProvider.js

feat: add useReset on WuiProvider for GlobalStyle

---

docs/pages/components/popover.mdx
packages/Popover/Trigger.js
packages/Popover/index.js
packages/Popover/styles.js
packages/Popover/usePopoverState.js

https://deploy-preview-799--welcome-ui.netlify.app/components/popover

feat: allow opening popover on hover

---

docs/components/SelectTheme.js
docs/pages/_app.js
packages/DropdownMenu/Item.js
packages/Select/index.js

* also remove some warnings on console from next
* add Provider from reakit to avoid server and client diff warnings

fix: remove ref warning on dropdown menu item

---

packages/Popover/Trigger.js
packages/Popover/index.js
packages/Popover/styles.js

Fix popover react warnings

---

packages/System/index.js

fix: system props messing with width and height

---

docs/pages/components/popover.mdx
packages/Popover/Trigger.js
packages/Popover/index.js

fix: mimic reakit behaviour on popover trigger hover

---

docs/components/Code.js
docs/components/HookForm.js
docs/components/Navigation.js
docs/package.json
docs/pages/components/field.mdx
docs/pages/components/hook-form.mdx
packages/Field/utils.js
yarn.lock

fix: checkbox error on field without connected

---

packages/Avatar/index.js
yarn.lock

feat: add possibility to set custom initial function on avatar

---

docs/pages/components/select.mdx

docs:  bring back all doc for select component

---

docs/pages/components/tag.mdx
packages/Core/theme/colors.js
packages/Tag/index.js
packages/Tag/theme.js
packages/Themes/Welcome/theme.js

feat: add new sub color 7

---

packages/Emoji/index.js

We'll monitor the cost of the CDN and we might use an external CDN if it's too expensive

feat: use WUI cdn for emojis

---

docs/components/Header.js
docs/components/Header.styled.js
docs/components/Headings.js
docs/components/Headings.styled.js
docs/components/Navigation.js
docs/components/TagVersion.js
docs/pages/_document.js
docs/utils.js

docs: add search with docsearch algolia

---

docs/pages/components/icons-font.mdx
docs/pages/components/icons.mdx

fix: icons reordering

---

.circleci/config.yml
package.json

fix: build on circle

---

packages/Swiper/index.js
packages/Swiper/index.test.js

https://output.jsbin.com/yepuxixenu
https://output.jsbin.com/habibevika
(the 7% missing are because of jsbin output)

fix: swiper roles & arias attributes

---

packages/Select/MultipleSelections.js
packages/Tag/index.js

https://output.jsbin.com/masofihoyi
https://output.jsbin.com/garixojusi
(the 20% missing are because of jsbin output)

fix: tag role attributes

---

packages/Loader/index.tsx

fix: make color prop optional for Loader component

---

packages/Core/theme/toggles.ts
packages/Toggle/styles.ts

https://www.loom.com/share/0a832a1fd9a34fd986faa7f85b767755

fix: toggle component styles on small viewport widths

---

packages/Field/layout.ts
packages/FileDrop/index.tsx
packages/Search/index.tsx
packages/Select/index.tsx
packages/Select/utils.ts
packages/System/index.tsx

some fixes on:
- System
- Field
- Select
- Search
- FileDrop

fix: v4.0.0 alpha.10

---

docs/pages/components/toast.mdx
icons/Attachment/package.json
packages/Toast/Growl.tsx
packages/Toast/Snackbar.tsx
packages/Toast/index.tsx
packages/Toast/styles.ts

https://www.loom.com/share/3bd0df15517549139d33e4f4eba8a13a

fix: Toast close button styles and add `hasCloseButton` prop

---

packages/Avatar/utils.ts

Prevent avatar to crash when name prop is missing

---

.circleci/config.yml
docs/components/ComponentsList/VersionSelector/index.js
docs/next.config.js

v3 branch is now deployed to welcome-ui.com/v3

feat: handle deployment of previous docs versions on same domain

---

docs/components/ComponentsList/VersionSelector/index.js

docs: update version list

---

packages/DatePicker/index.tsx
packages/DateTimePicker/index.test.js
packages/DateTimePicker/index.tsx
packages/DateTimePickerCommon/utils.ts

fix: timeIntervals prop not working properly

---

docs/pages/upgrade.mdx
package.json
packages/Core/theme/core.ts
packages/Core/theme/radii.ts
packages/Core/theme/types.ts
packages/Core/theme/typography.ts
packages/Text/index.test.tsx
packages/Text/styles.ts
yarn.lock

feat: add mobile size for headings in text component

---

docs/components/Homepage/Expectations.js
docs/components/Homepage/Stats.js
docs/components/Mdx/Pagination/index.js
docs/pages/index.js
packages/Text/styles.ts

docs: fix mobile homepage

---

packages/Radio/index.tsx
packages/RadioGroup/index.tsx

fix: radio group with hint

---

docs/components/Layouts/Docs/index.js
docs/components/Mdx/Headings/index.js
docs/components/Mdx/Showcase/Item.js
docs/pages/index.js
packages/Core/theme/drawers.ts
packages/Core/theme/modals.ts
packages/Modal/index.tsx

fix: space 50 to 5xl

---

docs/components/Header/ThemeSelector.js
docs/pages/components/drawer.mdx
docs/pages/components/modal.mdx
packages/Core/theme/modals.ts
packages/Modal/Close.tsx
packages/Modal/index.tsx
packages/Modal/styles.ts
packages/Themes/Welcome/theme.ts

fix: scroll on safari for Modal

---

LICENSE

chore: update year license

---

docs/components/ComponentsList/items.js
docs/components/Mdx/Code/index.js
docs/pages/404.js
docs/pages/components/flex.mdx
packages/Flex/.npmignore
packages/Flex/CHANGELOG.md
packages/Flex/README.md
packages/Flex/index.test.tsx
packages/Flex/index.tsx
packages/Flex/package.json
packages/Flex/rollup.config.js
packages/Flex/tsconfig.json

feat: add Flex component

---

docs/components/Mdx/Showcase/Item.js
packages/DropdownMenu/index.tsx
packages/Emoji/index.tsx
packages/EmojiPicker/index.tsx
packages/FileDrop/index.tsx
packages/FileUpload/index.tsx
packages/Group/index.tsx
packages/Loader/index.tsx
packages/Popover/index.tsx
packages/Select/index.tsx

docs: bring back missing descriptions

---

docs/pages/components/drawer.mdx
packages/Core/utils/base.ts

style: remove font size changing on small tablet

---

packages/Core/theme/paginations.ts
packages/Pagination/styles.ts
packages/Themes/Welcome/theme.ts

fix: pagination dots style

---

docs/components/ComponentsList/items.js
docs/components/Mdx/Code/index.js
docs/pages/components/grid.mdx
docs/pages/upgrade.mdx
packages/Flex/index.tsx
packages/Grid/.npmignore
packages/Grid/CHANGELOG.md
packages/Grid/Item.tsx
packages/Grid/README.md
packages/Grid/index.test.tsx
packages/Grid/index.tsx
packages/Grid/package.json
packages/Grid/rollup.config.js
packages/Grid/tsconfig.json

feat: add Grid component

---

docs/pages/upgrade.mdx
packages/Core/theme/core.ts
packages/Core/theme/types.ts
packages/Core/theme/typography.ts

feat: bring back textsTextTransform theme utility

---

docs/components/ComponentsList/items.js
docs/components/Mdx/Code/index.js
docs/pages/components/aspect-ratio.mdx
docs/pages/components/shape.mdx
docs/pages/upgrade.mdx
packages/AspectRatio/.npmignore
packages/AspectRatio/CHANGELOG.md
packages/AspectRatio/README.md
packages/AspectRatio/index.test.tsx
packages/AspectRatio/index.tsx
packages/AspectRatio/package.json
packages/AspectRatio/rollup.config.js
packages/AspectRatio/styles.ts
packages/AspectRatio/tsconfig.json

feat: add AspectRatio component

---

docs/components/Homepage/Components.js

docs: add links on components showcase

---

docs/pages/components/aspect-ratio.mdx
scripts/watch.js

chore: fix watch script

---

docs/components/Head.js
docs/pages/components/button.mdx
packages/Files/index.test.ts

docs: add new banner image

---

docs/components/Header/NavBar/index.js
docs/components/Header/NavBar/styles.js
docs/components/Layouts/index.js
docs/pages/blog.js

To merge when article is online :)

docs: add blog page

---

packages/Label/styles.ts

fix: long label on checkbox and toggle components

---

docs/components/Mdx/Code/index.js
docs/package.json
yarn.lock

docs: fix code view and upgrade react-live

---

docs/pages/components/input-text.mdx

docs: fix inputs

---

packages/Breadcrumb/index.tsx

fix: breadcrumb null child

---

packages/DropdownMenu/Item.tsx
packages/Tabs/TabList.tsx
packages/Tabs/TabPanel.tsx
packages/Tabs/index.tsx

Finally, reakit components using "render props" pattern accept xstyled props 🙈

fix: reakit components typing with render props

---

docs/pages/blog.js

docs: add podcast post

---

packages/Core/theme/buttons.ts
packages/Core/theme/defaultFields.ts

fix: v5 after failed rebase

---

.github/workflows/demo-link.yml

👀 [Visit Preview](https://ci-demo-link--welcome-ui.netlify.app)

ci: add demo link on PR description

---

packages/Tabs/styles.ts

👀 [Visit Preview](https://fix-tab-styledprops--welcome-ui.netlify.app)

fix: tab styledprops forwarded

---

docs/pages/installation.mdx

---
👀 [Visit Preview](https://docs-typescript--welcome-ui.netlify.app)

docs: add doc for typescript installation

---

packages/Core/theme/paginations.ts
packages/Pagination/index.tsx
packages/Pagination/styles.ts
packages/Pagination/utils.ts
packages/Themes/Welcome/theme.ts

#1273 
Welcome Theme
Dark Theme
When pageCount is smaller then RANGE
https://feat-pagination-1273--welcome-ui.netlify.app

feat Pagination v5

---

docs/components/Footer.js
docs/components/IconsList/Item.js
docs/components/IconsList/Item.styles.js
docs/components/Mdx/Dependencies/Item.js
docs/components/Mdx/Headings/styles.js
docs/components/Mdx/Showcase/Item.js
docs/components/Mdx/Showcase/index.js
docs/pages/components/box.mdx
docs/pages/components/loader.mdx
docs/pages/installation.mdx
packages/Button/index.test.tsx
packages/Core/theme/buttons.ts
packages/Core/theme/checkboxes.ts
packages/Core/theme/colors.ts
packages/Core/theme/core.ts
packages/Core/theme/dateTimePickerCommon.ts
packages/Core/theme/defaultFields.ts
packages/Core/theme/radios.ts
packages/Core/theme/radiosTabs.ts
packages/Core/theme/selection.ts
packages/Core/theme/swipers.ts
packages/Core/theme/tabs.ts
packages/Core/theme/tags.ts
packages/Core/theme/toggles.ts
packages/Label/styles.ts
packages/Themes/Welcome/theme.ts

chore: fix primary colors

---

.github/workflows/demo-link.yml
.github/workflows/pull_request_opened.yml
.github/workflows/pull_request_review.yml

ci: add label actions

---

docs/components/Colors.js
docs/components/Header/index.js
docs/components/Homepage/Expectations.js
docs/components/Mdx/Props.js
docs/components/Mdx/index.js
docs/components/Spacing.js
docs/pages/components/aspect-ratio.mdx
docs/pages/components/drawer.mdx
docs/pages/components/swiper.mdx
packages/EmojiPicker/index.tsx

> **Note**
> Interface hydration problems come from the fact that NextJs will make a `diff` between what was generated on the server side and what is generated on the client side.
What is still problematic :

fix: hydration initial UI

---

docs/pages/components/tabs.mdx
packages/Core/theme/tabs.ts
packages/Tabs/TabList.tsx
packages/Tabs/index.tsx
packages/Tabs/styles.ts

Issue #1472 : 
---
👀 [Visit Preview](https://feat-tabs--welcome-ui.netlify.app)

feat: tabs

---

docs/constants.js
docs/pages/components/tooltip.mdx
packages/Core/theme/tooltips.ts
packages/Tooltip/index.tsx
packages/Tooltip/styles.ts

- Updated the styling
- Added the fade/slide-in animation with 4 different directions depending on the placement property
- Slide-in disabled in the property `fixed` is used or if placement's value is  `auto-*`
👀 [Visit Preview](https://v5-tooltip-1465--welcome-ui.netlify.app)

feat: tooltip

---

docs/components/Header/ThemeSelector.js
docs/pages/upgrade.mdx
packages/Badge/styles.ts

fix: add missing system on badge style

---

docs/components/Header/index.js
docs/components/Layouts/Docs/index.js
docs/components/ThemeHelper.js

docs: add button to open theme documentation modal

---

docs/components/ComponentsList/index.js
packages/Slider/package.json

fix: component Slider package

---

docs/components/ThemeConfiguration/index.js
docs/components/ThemeHelper.js
docs/pages/upgrade.mdx

docs: add colors entries

---

packages/Swiper/index.test.tsx
packages/Swiper/index.tsx

Bugfix for this issue : https://github.com/WTTJ/welcome-ui/issues/1706

fix: change disabled condition of next button for Swiper

---

packages/Core/theme/modals.ts
packages/Modal/Close.tsx
packages/Modal/index.tsx
packages/Modal/styles.ts

* Close button position now sticks to the mockups
* style props are working and don't get overiden
*  paddings are fixed between header, content and footer
Signed-off-by: Diane Guillot <diane.guillot@wttj.co>

fix: modal styles and style props

---

packages/Drawer/styles.ts

fix: drawer style props

---

packages/Slider/package.json

chore: fix build

---

docs/components/ComponentsList/index.js
docs/components/ComponentsList/styles.js
docs/context/themeConfiguration.js
docs/pages/components/link.mdx
packages/Core/theme/colors.ts
packages/Core/theme/links.ts
packages/Core/theme/underline.ts
packages/Link/index.test.tsx
packages/Link/index.tsx
packages/Link/package.json
packages/Link/styles.ts

feat: rework link component

---

docs/components/IconsList/icons.js

docs: missing information outline icon

---

packages/Modal/Header.tsx

fix: modal header title type

---

packages/Toast/index.tsx

fix: toast component prop type

---

packages/Checkbox/styles.ts
packages/Core/theme/checkboxes.ts
packages/Core/theme/defaultFields.ts

fix: checkbox check color

---

docs/pages/upgrade.mdx

docs: add missing upgrade documentation for typography

---

.circleci/config.yml

chore: fix circle-ci security

---

packages/IconFont/package.json

docs: upgrade link to icons.font component

---

docs/pages/components/toast.mdx
packages/Toast/index.tsx

feat: upgrade default position for Toast Growl

---

docs/pages/components/alert.mdx
docs/pages/upgrade.mdx
packages/Alert/index.tsx
packages/Alert/package.json
packages/Alert/styles.ts
packages/Toast/Growl.tsx

https://user-images.githubusercontent.com/50322149/212049993-01e1635f-83e3-4981-a93d-944615b337f6.mov

feat: add CloseButton to Alert

---

packages/Tag/index.tsx

fix: link on tag component

---

packages/VariantIcon/index.tsx

chore: change icon for success variant

---

packages/Modal/index.tsx

fix: modal ariaLabel prop not being forwarded correctly to dom element

---

docs/components/Header/NavBar/index.js
docs/components/Header/index.js
docs/pages/blog.js

docs: add artisan developpeur podcast on blog page

---

scripts/core.sh

the previous method fails cf https://app.circleci.com/pipelines/github/WTTJ/welcome-ui/5755/workflows/92eb985a-db88-41b5-a717-f1003544e2af/jobs/32234?invite=true#step-104-22

fix: (build:core) git current branch

---

docs/pages/upgrade.mdx
packages/Tooltip/index.tsx

- Add a div around the Children of the tooltip

fix: tooltip not triggered

---

docs/pages/components/tooltip.mdx
packages/Core/theme/tooltips.ts

fix: padding top and bottom on tooltip

---

packages/Tag/index.tsx

related issue https://github.com/WTTJ/welcome-ui/issues/1904

fix(Tag): onRemove fire twice

---

packages/Button/styles.ts

fix: remove font weight on button icon to avoid bold icon

---

packages/Modal/Content.tsx

fix: modal body ref check

---

docs/components/Mdx/Props.js
docs/pages/components/swiper.mdx
docs/pages/upgrade.mdx
packages/Swiper/package.json
packages/Swiper/src/index.tsx
packages/Swiper/src/styles.ts
packages/Swiper/tests/index.test.tsx

Related issue: https://github.com/WTTJ/welcome-ui/issues/1899

feat: new swiper for wui v5

---

packages/DropdownMenu/src/Arrow.tsx

fix: arrow position on dropdownMenu

---

packages/Swiper/package.json
yarn.lock

chore: add missing lodash.debounce dep to Swiper

---

packages/Modal/src/Content.tsx
packages/Modal/tests/index.test.tsx

Related issue: https://github.com/WTTJ/welcome-ui/issues/1912

fix: modal content children type

---

packages/Drawer/src/index.tsx
packages/DropdownMenu/src/index.tsx
packages/EmojiPicker/src/index.tsx
packages/Modal/src/index.tsx
packages/Popover/src/index.tsx
packages/System/src/index.tsx
packages/Tabs/src/index.tsx

fix https://github.com/WTTJ/welcome-ui/issues/2085

fix: reakit state props

---

docs/public/robots.txt

chore: add a robots.txt to disallow old versions

---

docs/pages/components/swiper.mdx
packages/Swiper/src/index.tsx
packages/Swiper/src/styles.ts

We already have the condition on pagination, we need this also on arrows.

feat: add dark ui on arrows on Swiper

---

packages/Field/package.json
packages/Field/src/index.tsx
packages/Popover/package.json
packages/Popover/src/Trigger.tsx
packages/Tabs/src/ActiveBar.tsx
packages/Tooltip/package.json
packages/Tooltip/src/index.tsx
packages/Utils/src/use-viewport.ts

fix: do not use useLayoutEffect on SSR

---

docs/components/GlobalStyle.js
packages/Core/src/theme/core.ts
packages/Core/src/theme/fonts.ts

fix: wrong font weight on work sans variable font

---

packages/DatePicker/package.json
packages/DateTimePicker/package.json
packages/DateTimePickerCommon/package.json
packages/TimePicker/package.json
yarn.lock

fix: bump react-datepicker to hide unwanted text

---

docs/pages/components/swiper.mdx
docs/pages/upgrade.mdx
packages/Accordion/package.json
packages/Button/package.json
packages/Checkbox/package.json
packages/Drawer/package.json
packages/Drawer/src/index.tsx
packages/DropdownMenu/package.json
packages/DropdownMenu/src/index.tsx
packages/Modal/package.json
packages/Picker/package.json
packages/Popover/package.json
packages/Radio/package.json
packages/RadioGroup/package.json
packages/RadioTab/package.json
packages/Swiper/src/index.tsx
packages/Swiper/src/styles.ts
packages/Swiper/tests/index.test.tsx
packages/Tabs/package.json
packages/Toggle/package.json
packages/Tooltip/package.json
yarn.lock

fix: typescript consistency naming

---

packages/Accordion/package.json
packages/Button/package.json
packages/Checkbox/package.json
packages/Drawer/package.json
packages/DropdownMenu/package.json
packages/Modal/package.json
packages/Picker/package.json
packages/Popover/package.json
packages/Radio/package.json
packages/RadioGroup/package.json
packages/RadioTab/package.json
packages/Tabs/package.json
packages/Toggle/package.json
packages/Tooltip/package.json
yarn.lock

`@ariakit/react@0.2.17` includes https://github.com/ariakit/ariakit/pull/2718

chore: upgrade ariakit

---

docs/components/Footer.js
docs/components/Header/ThemeSelector.js
docs/components/Header/index.js
docs/components/Homepage/Components.js
docs/components/Homepage/Expectations.js
docs/pages/_document.js
docs/pages/components/toggle.mdx
docs/pages/index.js

fix: accessibitily on homepage and add example for toggle component

---

docs/components/ComponentsList/index.js
docs/pages/components/modal.mdx
docs/pages/upgrade.mdx

docs: add example for onClose option on useModal

---

packages/Tag/src/index.tsx

feat: remove listitem on tag for accessibility

---

packages/Core/src/theme/tooltips.ts

feat: add stroke on Tooltip

---

jest.config.js
package.json
yarn.lock

Before:
```
Test Suites: 13 passed, 13 total
Tests:       59 passed, 59 total
Snapshots:   0 total
Time:        44.268 s
```
After: 
```
Test Suites: 13 passed, 13 total
Tests:       59 passed, 59 total
Snapshots:   0 total
Time:        22.906 s
```
:rocket:

feat: add @swc/jest

---

.github/workflows/release.yml

fix: release auto tag

---

packages/Drawer/src/styles.ts

fix https://github.com/WTTJ/welcome-ui/issues/2287

fix: drawer width on mobile

---

.github/workflows/release.yml

ci: fix auto release on tag publish

---

packages/Radio/src/index.tsx
packages/Radio/src/styles.ts

fix: misaligned radio on RadioGroup

---

docs/pages/components/date-picker.mdx
packages/DateTimePickerCommon/src/CustomPopper.tsx

Improve the style of the month datepicker.

fix: improve style of month datepicker

---

.circleci/config.yml
packages/Core/src/utils/font.ts
scripts/webfont-build.js
scripts/webfont-deploy.sh

Fixes https://github.com/WTTJ/welcome-ui/issues/2378

fix: build and publish woff and woff2 files

---

packages/Accordion/src/styles.ts
packages/Tag/src/styles.ts

Fixes https://github.com/WTTJ/welcome-ui/issues/2383

fix: "unrecognised props" ssr warnings

---

packages/Drawer/src/styles.ts

Adresses : https://github.com/WTTJ/welcome-ui/issues/2391

Feat: remove fast transition on drawer

---

docs/components/Header/styles.js
docs/pages/components/toggle.mdx
packages/Checkbox/src/index.tsx
packages/Core/src/theme/toggles.ts
packages/Toggle/src/index.tsx
packages/Toggle/src/styles.ts

https://github.com/WTTJ/welcome-ui/assets/19819523/a81757e4-d360-4c52-ae96-12d6c7aed45f

feat: add size and icons for toggle component

---

CHANGELOG.md
docs/pages/components/modal.mdx
lerna.json
packages/Modal/CHANGELOG.md
packages/Modal/package.json
packages/Modal/src/Assets/AssetWithTitle.tsx
packages/Modal/src/Assets/Backdrop.tsx
packages/Modal/src/Assets/Iframe.tsx
packages/Modal/src/Assets/index.tsx
packages/Modal/src/Assets/styles.ts
packages/Modal/src/index.tsx
packages/Modal/src/styles.ts
packages/Swiper/CHANGELOG.md
packages/Swiper/package.json
packages/Swiper/src/index.tsx
packages/Swiper/src/styles.ts

https://github.com/WTTJ/welcome-ui/assets/50322149/16a1d9aa-7d15-48ab-be07-9c90fd8b0e6c

feat: add news AssetModal components for picture, video and swiper Modal

---

packages/Select/src/index.tsx
packages/Select/tests/index.test.tsx

before:
https://github.com/WTTJ/welcome-ui/assets/36373219/c9bc1ab1-a2f3-4c25-93eb-b2543c135ec8
after:
https://github.com/WTTJ/welcome-ui/assets/36373219/50890e61-a9a5-4159-a33c-f8b45bc1b95d

fix(select): onChange should return value instead of label when groupsEnabled

---

packages/Tooltip/src/index.tsx

fix: tooltip crash on ariakit 0.43

---

docs/pages/components/button.mdx
packages/Button/package.json
packages/Button/src/index.tsx
packages/Button/tests/index.test.tsx
yarn.lock

https://github.com/WTTJ/welcome-ui/assets/36373219/5806dad0-3004-4bec-be51-d2fe93fd9fee

feat(button): add loading state

---

packages/Text/docs/examples/withDash.tsx
packages/Text/docs/index.mdx
packages/Text/docs/properties.json
packages/Text/src/index.tsx
packages/Text/src/styles.ts
scripts/watch.js
utils/tests.tsx
website/build-app/examples.js

feat: add withDash property on Text headings

---

packages/Core/src/theme/tabs.ts
packages/Tabs/src/styles.ts

fix(Tabs): update gap small size [WUI-19]

---

lerna.json
packages/ButtonGroup/docs/properties.json
packages/ButtonGroup/package.json
packages/Core/package.json
packages/Core/src/theme/tags.ts
packages/DatePicker/package.json
packages/DateTimePicker/package.json
packages/DateTimePickerCommon/package.json
packages/Drawer/docs/properties.json
packages/Drawer/package.json
packages/DropdownMenu/package.json
packages/FileUpload/package.json
packages/Modal/docs/properties.json
packages/Modal/package.json
packages/PasswordInput/docs/properties.json
packages/PasswordInput/package.json
packages/Select/package.json
packages/Tag/docs/examples/variants.tsx
packages/Tag/docs/properties.json
packages/Tag/package.json
packages/Tag/src/index.tsx
packages/TimePicker/package.json

chore(tag): add primary variant [WUI-77]

---

packages/Alert/docs/examples/close-button.tsx
packages/Alert/docs/examples/cta.tsx
packages/Alert/docs/examples/sizes.tsx
packages/Alert/docs/examples/title.tsx
packages/Alert/docs/examples/variants.tsx
packages/Alert/docs/index.mdx
packages/Alert/docs/properties.json
packages/Alert/src/Title.tsx
packages/Alert/src/index.tsx
packages/Alert/src/styles.ts
packages/Alert/tests/index.test.tsx
packages/Core/src/theme/alerts.ts
website/build-app/examples.js

Fix elements alignement when there is not Title
**Before**

fix(alert): align title when no description

---

packages/Drawer/docs/examples/asset.tsx
packages/Drawer/docs/index.mdx
packages/Drawer/docs/properties.json
packages/Drawer/package.json
packages/Drawer/src/AssetDrawer/Header.tsx
packages/Drawer/src/AssetDrawer/index.tsx
packages/Drawer/src/AssetDrawer/styles.ts
packages/Drawer/src/index.tsx
packages/Drawer/tests/index.test.tsx
website/build-app/examples.js

https://github.com/user-attachments/assets/ed16cb6e-0eba-4ea8-a3a9-8849a66748d6

feat: add AssetDrawer sub component

---

lib/src/components/Swiper/index.tsx

fix: swiper accessibility issue

---

package.json
yarn.lock

chore: fix peer for vitest eslint

---

lib/src/components/Link/styles.ts

fix: link props should be forwarded to UniversalLink

---

lib/src/components/Link/styles.ts

fix: link syle props not working with an as prop

---

lib/package.json

fix: change priority order of exports

---

package.json
website/package.json
yarn.lock

This PR aims at fixing our vulnerabilities:
- next for our website | [changelog](https://github.com/WTTJ/welcome-ui/pull/2802)
- eslint globally | [changelog](https://github.com/eslint/eslint/compare/v9.24.0...v9.35.0)
No breaking changes, CI is still passing
N/A
N/A
N/A

chore(yarn audit): fix vulnerabilities

---

eslint-suppressions.json
eslint.config.mjs
lib/src/components/PasswordInput/ToggleButton.tsx
lib/src/components/PasswordInput/docs/examples/overview.tsx
lib/src/components/PasswordInput/docs/index.mdx
lib/src/components/PasswordInput/docs/properties.json
lib/src/components/PasswordInput/index.tsx
lib/src/components/PasswordInput/tests/index.test.tsx
website/build-app/examples.js
website/build-app/utils/examples-page-exporter.ts
website/loaders/generate-examples.js

chore: migrate PasswordInput

---

lib/src/components/Avatar/tests/index.test.tsx
lib/src/components/Toggle/toggle.module.scss

This pull request adds @layer directive around `Toggle` component's CSS.

Chore(Toggle): wrap toggle css with layer

---

lib/src/components/AspectRatio/aspect-ratio.module.scss
lib/src/components/AspectRatio/docs/examples/map.tsx
lib/src/components/AspectRatio/docs/examples/overview.tsx
lib/src/components/AspectRatio/docs/examples/ratio.tsx
lib/src/components/AspectRatio/docs/examples/video.tsx
lib/src/components/AspectRatio/docs/index.mdx
lib/src/components/AspectRatio/docs/properties.json
lib/src/components/AspectRatio/index.tsx
lib/src/components/AspectRatio/tests/index.test.tsx
lib/src/components/AspectRatio/types.ts
website/app/global.css
website/build-app/examples.js

chore: migrate AspectRatio

---

lib/src/components/InputText/docs/properties.json
lib/src/components/InputText/index.tsx
lib/src/components/InputText/input-text.module.scss
lib/src/components/InputText/types.ts
lib/src/components/PasswordInput/docs/properties.json
lib/src/components/Textarea/docs/properties.json
lib/src/components/Textarea/index.tsx
lib/src/components/Textarea/textarea.module.scss
lib/src/components/Textarea/types.ts

The pull request is to improve the types and styles of textarea and input text component to be align with recent decisions such as remove the default variant or to add some missing props like className to override when needed.

chore: improve textarea and input text type and style

---

lib/src/components/Drawer/AssetDrawer/asset-drawer.module.scss
lib/src/components/Drawer/drawer.module.scss
lib/src/components/Swiper/swiper.module.scss

fix(imports): fix theme utils import paths

---

lib/src/components/Modal/Assets/AssetTitle.tsx
lib/src/components/Modal/Assets/assets.module.scss
lib/src/components/Modal/components/Footer.tsx
lib/src/components/Modal/components/Header.tsx
lib/src/components/Modal/modal.module.scss
lib/src/components/Popover/docs/properties.json

This pull request embraces order

chore: use component based css instead of tailwind classes

---

.dev-releases/publish.mjs
.dev-releases/version.mjs
eslint-suppressions.json
lib/src/components/Card/Cover.tsx
lib/src/components/Card/docs/examples/content.tsx
lib/src/components/Card/docs/properties.json
lib/src/components/Card/index.test.tsx
lib/src/components/Card/types.ts
lib/src/components/Drawer/AssetDrawer/asset-drawer.module.scss
lib/src/components/Drawer/AssetDrawer/index.tsx
lib/src/components/Drawer/AssetDrawer/types.ts
lib/src/components/Drawer/docs/examples/asset.tsx
lib/src/components/Drawer/docs/properties.json
lib/src/components/FileDrop/components/FilePreview.tsx
lib/src/components/FileDrop/components/Message.tsx
lib/src/components/FileDrop/filedrop.module.scss
lib/src/components/FileDrop/index.tsx
lib/src/components/FileDrop/utils.ts
types/styled.d.ts

This pull request introduces accessibility improvements, refactors styling for consistency, and enhances type safety and documentation across several components. The most significant changes are the addition of an `alt` prop to the `Card.Cover` component for better accessibility, updates to the `AssetDrawer` to clarify `maxWidth` usage, and the refactoring of the `FileDrop` component to use CSS modules for styling and safer event handling.
**Accessibility improvements:**
* Added required `alt` prop to `Card.Cover` for improved accessibility, updated usage examples, tests, and type definitions to reflect this change (`lib/src/components/Card/Cover.tsx`, `lib/src/components/Card/docs/examples/content.tsx`, `lib/src/components/Card/index.test.tsx`, `lib/src/components/Card/types.ts`, …

Chore: wui styles improvements
