docz/CodeEditor.styled.js

fix: add margins to CodeEditor except on DropdownMenu to avoid warnings

---

packages/Box/doc.mdx
packages/Box/index.js
packages/Stack/index.test.js
packages/System/index.test.js

⚠️ A caveat is that `toHaveStyleRule` doesn't work with `<Box>` anymore, I tried other solutions and they didn't work, e.g:
```jsx
import styled from '@xstyled/styled-components'
export const Box = styled.box``
```
```jsx
import { Box as XStyledBox } from '@xstyled/styled-components'
export const Box = styled(XStyledBox)``
```
But the fix is quite simple, e.g: https://github.com/WTTJ/welcome-ui/pull/566/files#diff-3b0b985ffc5b2bd14071e7fc664710ccL27-R27

Use xstyled's box instead of system

---

packages/Tabs/doc.mdx
packages/Tabs/index.js
packages/Tabs/index.test.js

On the Reakit's `TabPanel` component, `stopId` has been renamed to `tabId`, not `id`.
Note also that both `Tab`'s `id` and `TabPanel`'s `tabId` aren't required anymore. Reakit now uses the DOM order to determine the `Tab`/`TabPanel` relationship, although you can still set `id`/`tabId`, especially if you render panels out of order.

fix(tabs): tab panel should use tabId prop instead of id

---

packages/FileDrop/FilePreview.js
packages/FileDrop/Preview.js
packages/FileDrop/doc.mdx
packages/FileDrop/index.js
packages/FileDrop/styles.js
packages/Files/index.js

Sometime in the url we don't have the type of the file, you can override with `forceFileType` set to `image`, `audio` or `video`.

fix: add forceFileType on fileDrop

---

packages/FileDrop/doc.mdx
packages/Group/index.js

I removed `isClearable` in the exemple of `FileDrop` because when it's not set, `Group` was trying to to access it: https://github.com/WTTJ/welcome-ui/blob/master/packages/Group/index.js#L10

fix: prevent error when some group children are undefined

---

packages/Field/theme.js
packages/Hint/index.test.js

(placeholder has the same color as the normal hint as well)

feat: redesign hint & placeholder

---

packages/Tabs/theme.js
packages/Tag/theme.js

feat: new tabs colors

---

packages/Checkbox/theme.js
packages/Core/theme/core.js
packages/Core/theme/defaultFields.js
packages/Field/theme.js
packages/Label/styles.js
packages/Label/theme.js
packages/Table/theme.js

- Create Label/theme.js and remove label key into Field/theme.js
- Use `tables` instead of `getTables` when the exported theme part is const (https://github.com/WTTJ/welcome-ui/pull/660#discussion_r437250275)

fix: change get* to only * for theme exports & use local theme for label

---

packages/Link/index.js

fix: don't override Link's Text fontWeight when using variant prop

---

packages/Icon/doc.mdx
packages/Icon/index.js
packages/Icon/styles.js
packages/Icon/theme.js
packages/Loader/doc.mdx
packages/Loader/index.js
packages/Loader/styles.js
packages/Loader/theme.js

* also remove underline from breadcrumb

fix: allow multiple types as size for Icon and Loader

---

packages/System/index.js
packages/Tabs/doc.mdx
packages/Tabs/styles.js
packages/Tabs/theme.js

fix: tablist boxShadow controllable via style props

---

docs/pages/components/swiper.mdx
packages/Swiper/index.js
packages/Swiper/index.test.js

Logic wasn't quite right when showing an even number of slides in a carousel with an odd number of slides.
https://www.loom.com/share/db88f37b581c4f6eaeaf2ef09f9569e7

fix: logic when numberOfSlides isn't divisible by slidesToSwipe

---

packages/Breadcrumb/Item.styles.js

Signed-off-by: Stéphane Robino <stephane@wttj.co>

fix: reset breadcrumb item direction

---

README.md
packages/Core/package.json
packages/Core/theme/core.js
packages/Core/theme/fonts.js
packages/Core/utils/base.js
packages/Core/utils/font.js
packages/Core/utils/work-sans.css
packages/DateTimePickerCommon/datePickerStyles.js

This means that…
1. Google will deliver the fonts reducing our CDN costs
2. 2 versions are served (`Latin` and `Latin extended`) so the initial font is smaller and the second font is only downloaded for SK/CS
Also set up fallbacks (`sans-serif`) and removed `ttf`

chore: use google fonts work sans

---

docs/pages/fields/file-upload.mdx
packages/FileUpload/index.js

I need to be able to replace the Button set in the render prop with a component to prevent the page to jump, so I added `file` & `onRemoveFile` to the render prop.
In addition, I've fixed an issue with `handleRemove` that was taking an event but was expected an index, which meant we were possibly removing the wrong one when multiple files were uploaded.
And last (and the one I'm really keen to get a review of) is that I added a key prop on the input based on the current files, to allow React to re-render this input thus allowing the user to upload a file, removing it & then re-adding it. I feel that it was needed because we can't manipulate the value of an input[type=file] element for security reasons.
https://www.loom.com/share/a35b315b60694936a63128d7567dbad1

Add render props to FileUpload (and fixes)

---

packages/FileDrop/utils.js

fix(file-drop): don't crash if invalid url passed to filedrop

---

docs/context/theme.js

The use of a legacy ```process.browser``` has been deprecated since june 2019 in favor of  ```typeof window ```
[Deprecated by this pull request](https://github.com/vercel/next.js/pull/7651)

Remove deprecated process.browser by typeof window

---

packages/Text/styles.js

`word-break` is set to `break-all` when you use `Text` component with `lines` prop set to `1`

fix: break all words on Text component with lines set to 1

---

packages/Popover/index.js
packages/Popover/styles.js

The bug is only visible when the `placement` is set to `top`
Before: 
After:

fix(popover): add system to ArrowItem in order to process h & w prop

---

packages/System/index.tsx

Utile pour typer un (styled-)component qui n'accepte que system par exemple : 
```
export const StyledTest = styled.div<WuiSystemProps>`
${system}
`
export const Test: React.FC<WuiSystemProps> = props => <SyledTest {...props} />
```
ça permet de pas ne pas inclure toutes les props de `xstyled/system` mais uniquement celle de notre `system`

chore: type custom system props

---

package.json

* Now that `yarn build` task includes `yarn webfont:build` there is no need to call it inside `yarn docs:deploy` (doublon)

fix: docs:deploy command

---

.circleci/config.yml
package.json

The goal behind these changes is to disable netlify's deploy since we have a very limited plan to build on netlify.
Deploys are now fully handled by circle with bigger machines than netlify (the build is a bit faster)
Deploy to production are now back and triggered only on tags
Deploy of previews are automatic on all branches with this url template: `https://${nameOfTheBranch}--welcome-ui.netlify.app`

chore: netlify deploy w/ circle

---

.circleci/config.yml

Before / after on the circle ci machine:

fix: persist Themes subfolders

---

packages/Core/theme/defaultFields.ts

Placeholder color used to be `nude.600` which isn't a color in the theme, so it defaulted to browser's defaults.
It was "fixed" by using `nude.500` which is way too light, so design asked us to replace it with `light.500`

fix: border & placeholder colors

---

packages/Core/theme/modals.ts
packages/Modal/index.tsx
packages/Modal/styles.ts

Useful to override props on `Modal.Content/Modal.Title/Modal.Cover/Modal.Footer`

refactoring: use JSX components instead styled on modal

---

packages/Toggle/styles.ts

Toggle acts weirdly when there is a performance bottleneck.
In this case, it's caused by algolia rerendering wayyy too many things:
[before](https://user-images.githubusercontent.com/243189/150114372-06217b86-c079-47c8-8261-92be76d5c923.mov)
I first used `:checked` & `:disabled` pseudo-classes to prevent having css generated at run time but it wasn't enough, the main culprit being the transition on the `left` property.
Here's a fixed version (still slow but not wonky):
[after](https://user-images.githubusercontent.com/243189/150114377-3507d52b-14e9-4a9b-9eec-9b372c33794e.mov)

Fix slow toggle

---

rollup.config.js

**Output actuel de `dist/box.es.js` :**
```
import _extends from '@babel/runtime/helpers/esm/extends';
import React from 'react';
import { x } from '@xstyled/styled-components';
import { forwardRef } from '@welcome-ui/system';
var Box = /*#__PURE__*/forwardRef(function (props, ref) {
return /*#__PURE__*/React.createElement(x.div, _extends({
ref: ref
}, props));
});
export { Box };
```
Ça me semble pas tiptop cette première ligne qui importe un helper depuis babel alors que ce n'est pas une peerDependecy de Box. (C'est la même chose sur tous les packages)
**Output de `dist/box.es.js` après le fix :** 
```
import React from 'react';
import { x } from '@xstyled/styled-components';
import { forwardRef } from '@welcome-ui/system';
function _extends() {
_extends = Object.assign || function …
```

fix: remove babel dependency from output

---

packages/Core/WuiProvider.tsx
packages/Core/index.ts

We need to use `useTheme` from "@xstyled/styled-components" instead of "@welcome-ui/core" in our applications to have a correctly typed theme according to our typescript configuration : https://www.welcome-ui.com/installation#typescript

fix: remove useless useTheme

---

docs/components/Header/index.js
docs/components/Header/styles.js
docs/pages/components/drawer.mdx
docs/pages/upgrade.mdx
packages/Core/theme/drawers.ts
packages/Drawer/index.test.tsx
packages/Drawer/index.tsx
packages/Drawer/styles.ts
packages/Modal/styles.ts

Drawer was reworked in order to work on Safari mobile as well on Chrome, desktop or mobile etc.
Here is the breaking changes we've introduced:
You have to wrap your Drawer with a <Drawer.Backdrop/> component. If you don't want this backdrop to appear, you have to give him a backdropVisible props set to "false" : backdropVisible={false}
We had a test on the children type of the Backdrop, to be sure to receive a drawer. Still, this was not working with Styled Drawer. So we remove this check. Be sure to pass a Drawer or styled Drawer as a children to Backdrop.
We sure plan to rework entirely for a future version.

Fix scroll drawer mobile

---

package.json
packages/DatePicker/package.json
packages/DateTimePicker/package.json
packages/DateTimePickerCommon/package.json
packages/TimePicker/package.json

We need to export the dependency `"@types/react-datepicker"` from `date-pickers...` packages to avoid installing this dependency on our applications

fix: date picker types export

---

package.json
rollup.config.js
yarn.lock

Currently, if you build the `@welcome-ui/search` package (the only one that uses **async/await** in our components), in the output, we can find this : 
```js
var searchResults = useCallback( /*#__PURE__*/function () {
var _ref2 = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee(value) {
var data;
return regeneratorRuntime.wrap(function _callee$(_context) {
while (1) {
...
```
But there is no import of `regeneratorRuntime` because we have babelHelpers in `inline` mode. 💀 :boom:
This new polyfill will create `_async` and `_await` function in the current file and use them like this :
```js
function _await(value, then, direct) { ... }
function _async(f) { ... }
var searchResults = useCallback(_async(function (value) {
return _invokeIgnored(function () {
if (minChars …
```

fix: add async/await inline polyfill

---

packages/Core/theme/core.ts

```jsx
<Box bg={{ _: 'primary.500', hover: 'dark.500' }}>Hover me</Box>
```
This will work now
cf https://xstyled.dev/docs/hover-focus-other-states

feat: allow to use xstyled states

---

packages/Core/theme/defaultFields.ts
packages/Select/index.test.tsx
packages/Select/index.tsx
packages/Select/styles.ts

- add disabled in Option
- mimic `isMultiple` style and behavior (when user try to select an already selected option)

feat: handle disabled options in select v.4

---

packages/DateTimePickerCommon/CustomInput.tsx
packages/DropdownMenu/Item.tsx
packages/EmojiPicker/index.tsx
packages/Popover/Trigger.tsx
packages/System/index.tsx
packages/Tabs/TabList.tsx
packages/Tabs/TabPanel.tsx
packages/Tabs/index.tsx

[States](https://xstyled.dev/docs/hover-focus-other-states/) works with prop like `backgroundColor` but doesn't work with HTML prop like `color`.
```tsx
// before
type A = BoxProps['color'] // string -> React.ComponentProps<"div"> inject `color` prop as string (dom property)
// now
type B = BoxProps[’color'] // xstyled type
```
Also, all Reakit components have bad types, they must not use forwardRef from @welcome-ui/system because the system is not injected

fix: omit html attributes overrided by xstyled

---

docs/pages/components/breadcrumb.mdx
packages/Breadcrumb/Item.styles.ts
packages/Breadcrumb/Item.tsx
packages/Breadcrumb/index.test.tsx
packages/Breadcrumb/index.tsx

To avoid TS problem, we removed renderChildrenAs property

fix: choose if last child is clickable on Breabdrumb

---

packages/Alert/index.tsx

Fixes Typescript error when passing using "as" with Alert Button

fix: alert button asComponent props

---

packages/DropdownMenu/Arrow.tsx

Warning after upgrade `@welcome-ui/dropdown-menu`
```
react.development.js:209 Warning: forwardRef render functions accept exactly two parameters: props and ref. Did you forget to use the ref parameter?
printWarning	@	react.development.js:209
error	@	react.development.js:183
forwardRef	@	react.development.js:1475
forwardRef2	@	system.es.js:63
(anonymous)	@	dropdown-menu.es.js:24
```

fix: missing ref dropdown arrow

---

docs/components/Layouts/Docs/index.js
docs/components/ThemeConfiguration/index.js
docs/components/ThemeHelper.js
docs/context/themeConfiguration.js
packages/Core/theme/core.ts
packages/Core/theme/types.ts

It's a bit difficult to remember the value and convert rem value to pixel regarding spacing, screens, font sizes, font weight, etc. it's like constant mental gymnastics 🤸‍♀️ 
Create an helper to display converted values 🚀 and be relaxed now 😎
How to display the helper : `CMD + I`
https://user-images.githubusercontent.com/9429420/187430395-9ba4e2ed-a8c6-4e6b-91c4-5e13c1cc0305.mov

feat: helper for theme configuration

---

packages/Search/index.tsx

Search component props are mistyped.
Currently `<Search w={200} />` will throw an error because, `w` doesn't exist in SearchProps definition, we need to use our own forwardRef and CreateWuiProps.

fix: type search props with wui props

---

packages/Core/utils/base.ts

As explain on this issue https://github.com/WTTJ/welcome-ui/issues/1543, we have a visual issue with `Toast` package when we use `useReset` prop to `WuiProvider` (you can find a demo if you want to reproduce this bug on issue link).
After some research, it seems that it comes from the CSS property `min-height` with `0`value in reset style. This style applies to `Toaster__message-wrapper` classname. And that's why, it doesn't work.
Unfortunately `toasted-notes` package doesn't provide any method to customize this classname or any other parents classname. That's why, I add some style on GlobalStyle to be sure reset style doesn't apply to this classname.
I'm not satisfied about this fix because it very dependant of `toasted-notes` package (if after an update this classname change, it will …

fix: toast issue with useReset prop to WuiProvider

---

packages/Loader/index.test.tsx
packages/Loader/styles.ts
utils/tests.js

fix: loader size prop

---

docs/components/App.js
docs/pages/_app.js
docs/pages/components/toast.mdx
docs/pages/upgrade.mdx
packages/Toast/ToastWrapper.tsx
packages/Toast/index.tsx
packages/Toast/package.json
packages/Toast/styles.ts
packages/Toast/utils.ts
yarn.lock

Hey! 🖖 
Je viens de remplacer le package `toasted-notes` par `react-hot-toast`. Celui-ci gère mieux les notifications en les montant au même endroit dans le DOM. De plus, j'ai utilisé la partie _headless_ du package qui a le moins de dépendance et nous permet de l'intégrer exactement comme on le souhaite. Malheureusement cela implique quelques breaking changes que j'ai essayé de limiter au maximum.
Voici la liste des changements majeurs :
- `useToast()` est _deprecated_. On peut encore l'utiliser mais clairement ce hook devient inutile. Avant on faisait :
```jsx
const toast = useToast()
return (
<Button onClick={() => toast(<div>Message</div>)}>
Show Toast
</Button>
)
```
Maintenant on peut directement importer et utiliser `toast()` :
```jsx
<Button onClick={() => …
```

feat: rework Toast component

---

docs/pages/components/icons-font.mdx
packages/Button/index.test.tsx
packages/Button/package.json
packages/Button/styles.ts
packages/Icon/index.tsx
packages/IconFont/index.tsx
stylelint.config.js

fix #1745 icons size inside buttons

---

packages/Avatar/utils.ts

fix: avatar getSeededColor util

---

docs/pages/components/link.mdx
packages/Link/styles.ts

feat: add possibility to inherit parent on a link

---

packages/Modal/Content.tsx
packages/Modal/Footer.tsx
packages/Modal/Header.tsx
packages/Modal/index.tsx
packages/Modal/styles.ts

Now, only the body is scrolling when the content is too big.
The header & the footer stay fixed in desktop and mobile device.
https://user-images.githubusercontent.com/36013102/212670883-7e451be3-bc11-4fe6-beb7-ae53df610c3a.mov

fix: modal scrolling with header and footer fixed

---

docs/pages/components/link.mdx
docs/pages/upgrade.mdx
packages/Link/index.tsx
packages/Link/styles.ts

- `isExternalLink` prop become `isExternal`
- wrap every `<span />` with *WrapWithText* (add the underline) fix https://github.com/WTTJ/welcome-ui/issues/1877
- refactoring

refactor: link isExternal prop & wrap span with underline

---

packages/Field/styles.ts
packages/Radio/styles.ts

Checkbox/radio and their labels now align to top :

fix: checkbox/radio alignment with long text label

---

packages/Core/theme/drawers.ts

This is a review from the design team:
https://github.com/WTTJ/welcome-ui/issues/1906
The difference of padding between the drawer title and the drawer content was a mistake.

fix: align title and content for drawer

---

packages/Tooltip/index.tsx

- Add display: inline-block to div surrounding the tooltip's Children

fix: add inline block property to div

---

packages/Modal/Content.tsx
packages/Modal/context.tsx
packages/Modal/index.tsx
packages/Modal/package.json
yarn.lock

Related issue: #1922 
As Reakit doesn't handle scrolling content we have to forward the modalState to the Modal.Content in order to check when the modal is visible and enable the scroll.
_Reakit issue:_ https://github.com/ariakit/ariakit/issues/469
I preferred to use a context to keep the logic internally and not expose a misleading prop which could be use in the implementation and also as we render children and not the Modal.Content directly, thanks to the context we avoid using `children.map` and `cloneElement`.

fix: modal scroll on mobile device

---

packages/Core/src/theme/labels.ts

We need to force label color because we got an issue on modal, the Modal.Body is in black-900 color and the label get the dark 900 color.

fix: force label color

---

docs/pages/components/tooltip.mdx
docs/pages/upgrade.mdx
packages/Tooltip/package.json
packages/Tooltip/src/index.tsx

Here, the `tabIndex` is injected into the wrapper of the child instead of the child. We must remove this wrapper.
Before:
After:
cf [reakit doc](https://reakit.io/docs/tooltip/#abstracting)
We added a div around the Children of the tooltip when the children has a disabled prop otherwise the tooltip does not trigger.

fix: tooltip children without wrapper

---

packages/DropdownMenu/src/Item.tsx

After upgrading to 5.0.0-alpha.22, we need to pass the props `state` and `{...state}`
```tsx
<DropdownMenu.Item {...menu} state={menu} />
```
We must remove `{...state}` on declaration

fix: dropdown-menu item type

---

packages/Shape/src/styles.ts

`<Shape position="absolute" />` doesn't work without `system` inside the styled component.

fix: missing system on shape

---

packages/Swiper/src/index.tsx

Related issue: https://github.com/WTTJ/welcome-ui/issues/1999
https://user-images.githubusercontent.com/19819523/223984497-c24b4cef-295a-4655-8f4d-e5ec54db5dc3.mov

fix: deactivate swiper scroll animation on first render

---

scripts/upgrade-packages-next.js
scripts/upgrade-v5.js

Unfortunately, `yarn upgrade-interactive --latest` does not work with the prerelease versions...
It is very boring to upgrade welcome-ui v5 (still in alpha), this script should help 🤗 
After the script:
(don't forget to run a `yarn install` after running this script)

chore: upgrade-packages-next script

---

packages/ButtonGroup/src/index.tsx
packages/ButtonGroup/tests/index.test.tsx

The goal of this PR is to allow us to write something like this:
```jsx
<ButtonGroup>
<Button>Foo</Button>
{hasBar && <Button>Bar</Button>}
</ButtonGroup>
```
instead of:
```jsx
{hasBar && (
<ButtonGroup>
<Button>Foo</Button>
<Button>Bar</Button>
</ButtonGroup>
)}
{!hasBar && (
<Button>Foo</Button>
)}
```
We already filter falsy values out here: https://github.com/WTTJ/welcome-ui/blob/master/packages/ButtonGroup/src/index.tsx#L23

Allow falsy children in <ButtonGroup>, fixes #1705

---

packages/Drawer/src/index.tsx

Quick fix while waiting for ariakit v2

fix: missing "as" prop on drawer.trigger

---

packages/Popover/src/index.tsx

Since the migration to `state=` for reakit components, some props have been lost in type definition because the Props are sometimes different from the state return
I think the popover is not the only component affected, we should create a task to do the same work on every reakit components having a state

fix(popover): reakit component props != from stateReturn

---

packages/Swiper/src/index.tsx

The recently applied fix: https://github.com/WTTJ/welcome-ui/pull/2052/files passed manual testing on simple configured swipers but it introduced a bug on swipers with multiple slides per view and at least 3 pages. 
Fix: properly round the whole result of nextPage's calculation. 
https://github.com/WTTJ/welcome-ui/assets/85453899/26fdec4c-d117-4569-8db5-d915ef7dbc03

Fix: rounding of swiper's nextPage calculation

---

packages/Avatar/src/utils.ts
packages/Avatar/tests/index.test.tsx

Current behavior:
```jsx
<Avatar name="Welcème Jungle" src={null} />
// initials "WM"
```
Desired behavior:
```jsx
<Avatar name="Welcème Jungle" src={null} />
// initials "WJ"
```

fix(avatar): getInitials break words with accent

---

packages/Breadcrumb/src/Item.tsx
packages/Slider/src/Range.tsx
packages/Slider/src/index.tsx

fix this warning in the browser console
`Warning: forwardRef render functions accept exactly two parameters: props and ref. Did you forget to use the ref parameter?`

fix: forward ref warnings

---

packages/Drawer/src/index.tsx
packages/Drawer/tests/index.test.tsx
packages/DropdownMenu/src/index.tsx
packages/Modal/src/index.tsx
packages/Modal/tests/index.test.tsx

related to: https://github.com/WTTJ/welcome-ui/pull/2083
The `Drawer.Trigger` throw errors when you add props of the "as" component:
```tsx
<Drawer.Trigger as={Button} variant="primary" state={state}>...</Drawer.Trigger>
```
Here, the prop "variant" will throw an error, if you remove it, it works.
This is because the `Drawer.Trigger` component doesn't use our custom `forwardRef` type (this type inject props of the as component in the current component, _here add the props of the `Button` in the `Drawer.Trigger`_)

fix: drawer trigger "as component" props

---

packages/Breadcrumb/src/Item.tsx
packages/Breadcrumb/src/styles.ts

https://github.com/WTTJ/welcome-ui/assets/33298885/619a4e60-fd7c-4b78-8382-4d729a065496

fix Breadcrumb: remove  vertical scroll

---

packages/DropdownMenu/src/Item.tsx
packages/DropdownMenu/src/index.tsx

The `as` prop is deprecated on Ariakit but we want to use the Welcome-UI `as` prop 👀

fix: remove & override "as" prop (ariakit)

---

packages/Slider/src/Range.tsx
packages/Slider/src/index.tsx
packages/Slider/tests/index.test.tsx

**FIX :**
- `disabled` props should disable the number inputs too
- onBlur after changing the number input value should update the slider position
- fix `values` labels position in Slider component
- ensure the respect of `min` and `max` when user update value using arrow keys
- fix yellow range position and length in Slider.Range when `min` and `max` are set and different from 0 and 100
fixes https://github.com/WTTJ/welcome-ui/issues/2168
https://github.com/WTTJ/welcome-ui/assets/33298885/5e43f576-60b5-4b9d-8b4a-fc5f3af3650f
https://github.com/WTTJ/welcome-ui/assets/33298885/4272b61d-68cc-4be8-85b1-b0fc98721d06

Fix(slider): connect input and slider position, disabled input, values style

---

docs/pages/theming/customize.mdx
packages/Core/src/utils/font.ts

Example usage:
```
export const fontFaces = {
'Work Sans': [
{
url: `${FONT_URL}/work-sans-variable-latin-ext`,
isVariable: true,
stretch: '75% 125%',
uniCodeRange:
'U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF',
weight: '400-600',
},
{
url: `${FONT_URL}/work-sans-variable-latin`,
isVariable: true,
stretch: '75% 125%',
uniCodeRange:
'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD',
weight: '400-600',
},
],
}
```
Fixes https://github.com/WTTJ/welcome-ui/issues/2208

chore: allow and apply unicodeRange

---

.circleci/config.yml
.github/workflows/release.yml

Fixes #1650 
We need to use a github action because `lerna version --create-release` need to have a github secret and this command is done on local, we don't won't other developers to have this token, this action is the solution :)

chore: add auto github release with changelog

---

packages/Modal/src/styles.ts

We need to add zIndex to avoid wrong zIndex from modal content

fix: zIndex on modal Header and Footer

---

packages/Swiper/src/styles.ts

We need to override the ghost button with important because on our case the background is white, and styled component doing wrong override here so we need to add important to be sure is overrided.

fix: swiper custom button background

---

packages/Tooltip/src/index.tsx
packages/Tooltip/src/styles.ts

Workaround for this issue: https://github.com/ariakit/ariakit/issues/2929

fix(tooltip): always visible after hover

---

packages/Modal/src/index.tsx
packages/Modal/tests/index.test.tsx

Fix https://github.com/WTTJ/welcome-ui/issues/2341
The first option is to remove the `onClose` prop from the `useModal` and render the same hook as the drawer:
```tsx
export function useModal(options?: UseModalProps): UseModal {
return Ariakit.useDialogStore({ animated: true, ..options })
}
```
The second option is to wrap the render of the hook with a `useMemo`, I decided to choose this one for prevent breaking changes, but I'm open to discussing it.
(I prefer the first option, but I don't know if the `onClose` prop is used by someone?)

fix(modal): not visible while updating state on open

---

packages/Tabs/src/ActiveBar.tsx

When bouding rect values are all 0 we have a divison of 0 / 0 which equals NaN.
To avoid this, I check for NaN

fix: avoid having js error because of NaN on tabs activebar

---

packages/DateTimePickerCommon/src/CustomPopper.tsx
packages/DateTimePickerCommon/src/index.tsx
packages/DateTimePickerCommon/src/styles.ts
packages/TimePicker/src/index.tsx
packages/TimePicker/src/styles.ts

Fixes #2305 
Hide unwanted aria message for DatePicker and TimePicker

fix: hide unwanted aria messages for date/time pickers

---

packages/Tag/src/index.tsx

I've added a `type="button"` to the remove button of a Tag, otherwise if this tag is in a form then it submits the form.

fix(tag): add default type to remove button

---

docs/pages/components/swiper.mdx
packages/Swiper/src/index.tsx

Items with `aria-hidden=true` have a `backgroundColor: tomato` 💅🏻 
before:
https://github.com/WTTJ/welcome-ui/assets/36373219/07e72cef-4640-464e-bc95-28ab723d4bd1
after:
https://github.com/WTTJ/welcome-ui/assets/36373219/47b828a6-46c0-42dd-862c-a34113658035

fix: swiper aria-hidden slide on last page

---

packages/DatePicker/src/index.tsx

Add an option to prevent the virtual keyboard from opening (useful on mobile).

feat(datepicker): add option to prevent virtual keyboard from opening

---

docs/pages/components/breadcrumb.mdx
packages/Breadcrumb/src/Item.styles.ts
packages/Breadcrumb/src/Item.tsx
packages/Breadcrumb/src/index.tsx
packages/Core/src/theme/breadcrumbs.ts

Following our design:
- Item without link must not have "hover" style
- Active item should have color to `dark-700` instead of `dark-900`
https://github.com/WTTJ/welcome-ui/assets/36373219/cc7e7144-7701-43e0-9d24-9457b549d9e0

feat(breadcrumb): items without link must be disabled

---

docs/pages/components/select.mdx
packages/Select/src/index.tsx
packages/Select/tests/index.test.tsx

Currently, when groups are enabled on the `<Select />`, the search only searches on the group labels and not on the options label 😞 
before:
https://github.com/WTTJ/welcome-ui/assets/36373219/b6f520b6-5f8c-4fff-9e4d-ff89989a5ef2
after:
https://github.com/WTTJ/welcome-ui/assets/36373219/4a815d00-0a3e-48a1-a5fd-84f3851d17e6

fix(select): allow to search on group options

---

packages/Modal/src/Header.tsx

rollback this PR https://github.com/WTTJ/welcome-ui/pull/2422
Actually, we have a lot of title like this: `title={<FormattedMessage ... }` in the Modal.Header and I'm not sur we want this BC
So we can rollback this one, and looking for a more suitable solution

fix: rollback modal header a11y

---

packages/Swiper/src/index.tsx
packages/Swiper/src/styles.ts

When swiper has "fullWidth" prop to true, [we display 2 additional items](https://github.com/WTTJ/welcome-ui/blob/81ec13a464e0469b5bc0719255ae12d3ae63e1e5/packages/Swiper/src/styles.ts#L174) on resolutions >1920px.  
But these 2 additional items displayed had the 'aria-hidden' property set to true, which prevented us from interacting with these items (such as clicking on a link).

fix: computation of slides per view when swiper is full width

---

packages/Select/src/index.tsx
packages/Select/src/styles.ts

Issue raised for the showcase editor by Jade :
- The icons and the dropdown arrow on the right should have the same color as the text when the select is in a disabled state, according to [the select design specs](https://www.figma.com/file/l9klusKgMYIp90BkLBE3K7/Forms?type=design&node-id=2310-2800&mode=design&t=lqcGfKRG02slaj3g-0)

Fix: use proper colors when the select is disabled

---

packages/Breadcrumb/src/index.tsx

An error in sentry has shown that `style` could be called on `undefined` here 👉 https://github.com/WTTJ/welcome-ui/blob/main/packages/Breadcrumb/src/index.tsx#L66
(the sentry error for those who have access 👉  https://wttj.sentry.io/issues/5458739338/?environment=production&project=1222380&query=is:unresolved+issue.priority:%5Bhigh,+medium%5D&statsPeriod=1h&stream_index=0)
This is just about fixing the error when no element.

fix: don't set translation if no element

---

docs/pages/components/button.mdx
docs/pages/theming/customize.mdx
package.json
packages/Core/src/theme/alerts.ts
packages/Core/src/theme/buttons.ts
packages/Core/src/theme/cards.ts
packages/Core/src/theme/core.ts
packages/Core/src/theme/defaultCards.ts
packages/Core/src/theme/defaultFields.ts
packages/Core/src/theme/radii.ts
packages/Core/src/theme/toasts.ts
packages/Core/src/theme/tooltips.ts
packages/MarkdownEditor/src/styles.ts
packages/RadioTab/src/styles.ts
packages/Shape/tests/index.test.tsx
packages/Tag/src/styles.ts
packages/Themes/Welcome/src/theme.ts
scripts/upgrade-radii.js
yarn.lock

feat: add new border radii theme and reset all on components

---

packages/Core/src/theme/tooltips.ts
packages/Tooltip/docs/examples/placement.tsx
packages/Tooltip/docs/examples/withArrow.tsx
packages/Tooltip/docs/index.mdx
packages/Tooltip/src/index.tsx
packages/Tooltip/src/styles.ts
website/build-app/examples.js

[new Tooltip figma](https://www.figma.com/design/TC5aahnPVDU1hhBcff037e/Feedback?node-id=2-890&t=U5KECT8ulj9zSnFz-0)
The arrow's position is based on the tooltip placement recovered from the store, and not the user prop. 
This garanties that the arrow's position is coherent with the tooltip's if it doesn't have enough space. 
https://github.com/WTTJ/welcome-ui/assets/85453899/ea58e3fa-7f8c-401f-b16b-830be38acf7c
https://github.com/WTTJ/welcome-ui/assets/85453899/f46bb833-510a-4334-8cdf-fa2097c22266

Chore: tooltip redesign

---

packages/Tag/src/index.tsx

PR to clean up a warning recurring in test files. I used a ternary rather than the `&&` notation to check for the childrenLength.

fix(Tag): use ternary for conditional prop

---

packages/FileDrop/docs/examples/custom-filename.tsx
packages/FileDrop/docs/index.mdx
packages/FileDrop/docs/properties.json
packages/FileDrop/src/FilePreview.tsx
packages/FileDrop/src/Preview.tsx
packages/FileDrop/src/index.tsx
website/build-app/examples.js

Add a new `fileName` prop to the `FileDrop` component, allowing users to display a custom file name in the preview instead of the default name extracted from the URL.  
This is useful when the actual file name is too complex or not representative of the file's content.

feat: allow to display custom file name in the preview of a FileDrop

---

website/build-app/components/IconsList/index.tsx
website/build-app/components/IconsList/styles.ts

https://github.com/user-attachments/assets/d0c98cf6-b139-466f-8827-0160abde4b69

Feat: click icon to copy component name

---

packages/Swiper/src/styles.ts

fix: swiper item width when there is less than x items

---

packages/Select/docs/examples/creatable-custom.tsx
packages/Select/src/styles.ts

[WUI-50: Add a pointer cursor to Select dropdown](https://linear.app/wttj/issue/WUI-50/add-a-pointer-cursor-to-select-dropdown)

Chore(Select): use pointer cursor when hovering select options [WUI-50]

---

README.md
lerna.json
packages/Core/package.json
packages/Core/src/theme/modals.ts
packages/DropdownMenu/package.json
packages/Modal/package.json
packages/Modal/src/styles.ts
packages/Themes/Dark/package.json
packages/Themes/Welcome/package.json
packages/Themes/WelcomeDark/package.json

When migrating to latest v5 version, we noticed an issue in the Modal style when:
- It contains a select and need to apply an overflow: "visible" property
- It also contains a Header and/or a Footer
Current:
Expected (tested on welcome-accounts-front)

fix(Modal): border radius and overflow

---

packages/Alert/docs/examples/cta.tsx
packages/Alert/docs/examples/is-full-width.tsx
packages/Alert/docs/examples/sizes.tsx
packages/Alert/docs/index.mdx
packages/Alert/docs/properties.json
packages/Alert/src/Title.tsx
packages/Alert/src/index.tsx
packages/Alert/src/styles.ts
packages/Alert/tests/index.test.tsx
packages/Core/src/theme/alerts.ts

https://github.com/user-attachments/assets/93f5578e-4a82-4a52-b516-197c3cb26617

feat: update alert component

---

lib/src/components/Toast/index.tsx

As discussed [here](https://wttj.slack.com/archives/C017KMZ4FBJ/p1736172619738689), I made the change to add a generic identifier in order to retrieve all the toast that must be persistent after opening a modal.
I choose this approach to ensure a clear separation between styling and functionality, avoids potential class name conflicts, and makes the selection of persistent toasts more reliable and maintainable. Also `data-wui-persistent` can be used in any other component that need to be persistent.

fix: ensure that toast can be identify as a persistent element

---

lib/src/components/Accordion/styles.ts

**Sizing and spacing adjustements**
- Title's`gap` decreased from `xxl` to `lg`
- Arrow button size increased from `24px` to `32px`
- Arrow button border radius increased to `16px` to keep roundeness
This PR changes are required have been requested and approuved by the designers for a wttj-front component. 
To test the gap value, you can create a accordion with a very long title. 
To test the arrow button, hover the title.

Chore(Accordion): increase arrow btn size and title gap [WUI-108]

---

.circleci/config.yml
website/build-app/components/VersionSelector/index.tsx
website/public/robots.txt

This pull request includes updates to support version 8 across various parts of the project. The changes primarily focus on updating version references in configuration files and components.
Version updates:
* [`.circleci/config.yml`](diffhunk://#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47L304-R304): Updated version filters to include `v8` and adjusted tag patterns to match the new version. [[1]](diffhunk://#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47L304-R304) [[2]](diffhunk://#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47L317-R317)
* [`website/build-app/components/VersionSelector/index.tsx`](diffhunk://#diff-b1730f043736fc685d6208de8a3da9089352f6f2f95a3b4dfeb08f776d5cb7d9R7-R11): Introduced a constant for …

docs: add v7 website

---

website/package.json
yarn.lock

This pull request includes a minor update to the `website/package.json` file. The change updates the version of the `next` package.
* [`website/package.json`](diffhunk://#diff-fae242fbf77a8a9d52625664bc36ea12316586f8a716b41137d897a2b7e3df76L23-R23): Updated the `next` package version from `14.2.21` to `14.2.25`.

fix: critical issue with nextjs

---

lib/src/components/Label/styles.ts

The asterisk associated with required field is missing, due to a missing css selector
- start your project locally
- Go to http://localhost:3020/components/field
- Scroll til the required example
- See you now have the asterisk next to the field label
BEFORE
AFTER

fix(field): add missing & selector in Label css

---

lib/package.json

fix: declaration files should be referenced as exportable for typescipt to generate declaration files of libraries using wui

---

lib/src/components/Tag/styles.ts

[WUI-116: Tags: missing padding when they are one character long](https://linear.app/wttj/issue/WUI-116/tags-selected-values-are-missing-padding-when-they-are-short)
Tags are not dispalyed properly when these two conditions are met:
- Content is one character -> the Tag uses Shape styles
- Tag has a onRemove handler -> adds padding to the tag's content 
This PR checks for onRemove before enabling the Shape styles
- Create a Tag with one character and an onRemove handler

Fix(Tags): do not use shape styles when onRemove is truthy

---

lib/src/components/Drawer/AssetDrawer/Header.tsx
lib/src/components/Drawer/AssetDrawer/index.tsx

We had an issue with the scrollbar overriding the parent drawer for the asset component.
- Go to http://localhost:3020/components/drawer
- Scroll the doc page to the latest example (AssetDrawer)
- Open it, try to scroll and see the scrollbar is not overriding its parent at the top of the drawer
BEFORE
https://github.com/user-attachments/assets/0c94320f-0dd9-4c29-9993-23cc0a115e8f
AFTER
https://github.com/user-attachments/assets/83d78152-7026-460d-a640-ea85e4c27186

fix: improve scrollbar style after review on front-components

---

lib/src/components/Card/styles.ts

The `Card` component has a malformed value for `overflow`
Before:
```
overflow: 'hidden';
```
After:
```
overflow: hidden;
```
1. Use card in page
2. Look at css for card

fix: remove quote marks from css value

---

.dev-releases/version.mjs
lib/src/components/Toggle/styles.ts

This pull request includes a small change to the `Wrapper` component in `lib/src/components/Toggle/styles.ts`. The change adds the `flex-shrink: 0;` CSS property to ensure the component does not shrink when space is constrained.

fix: toggle size with a long hint and label

---

website/app/components/[id]/layout.tsx
website/app/components/[id]/page.tsx
website/app/components/[id]/props/page.tsx
website/app/foundations/[id]/[subPage]/page.tsx
website/app/foundations/[id]/layout.tsx
website/app/foundations/[id]/page.tsx
website/app/layout.tsx
website/build-app/types.ts
website/build-app/utils/pages-exports.ts
website/package.json
website/tsconfig.json
yarn.lock

We had to update our docs' NextJs to at least version 15.2.4 because of vulnerabilities with older version. 
This PR: 
- Bumps Next version
- Updated how our different layout component access params, [next docs](https://nextjs.org/docs/messages/sync-dynamic-apis)
- Fixes [hydration errors with next-themes](https://ui.shadcn.com/docs/dark-mode/next) 
- poke around
- open the last component you're worked on to ensure it still behaves the same

Chore(Docs): update next version to fix vulnerabilities

---

lib/package.json
lib/src/components/DatePicker/docs/examples/react-date-picker.tsx
lib/src/components/DatePicker/docs/properties.json
lib/src/components/DatePicker/index.tsx
lib/src/components/DateTimePicker/docs/properties.json
lib/src/components/DateTimePicker/index.tsx
lib/src/components/DateTimePicker/tests/index.test.tsx
lib/src/components/DateTimePicker/utils.ts
lib/src/components/DateTimePickerCommon/CustomInput.tsx
lib/src/components/DateTimePickerCommon/styles.ts
lib/src/components/DateTimePickerCommon/utils.ts
lib/src/components/TimePicker/docs/examples/react-date-picker.tsx
lib/src/components/TimePicker/docs/properties.json
lib/src/components/TimePicker/index.tsx
lib/tests/setup.ts
yarn.lock

This Pr updates the datepicker to its last version. 
Only breaking potential breaking changes I could find was: 
- on [v5.0.0] (https://github.com/Hacker0x01/react-datepicker/releases/tag/v5.0.0) -> Migrate from Popper.js to Floating-UI
- on [v6.6.0] (https://github.com/Hacker0x01/react-datepicker/releases/tag/v6.6.0) -> feat: Replaced classnames with clsx 
I observed no change in behavior for the datepicker 
- Mess round with the datepicker components 
- Install a dev release to your project and run your tests suites

Chore(DatePicker): update datepicker version

---

lib/src/components/Breadcrumb/theme.ts
lib/src/components/Link/theme.ts
lib/src/components/Slider/Range.tsx
lib/src/components/Slider/index.tsx
lib/src/components/Slider/styles.ts
lib/src/components/Tabs/theme.ts
lib/src/theme/defaultFields.ts

This pull request updates the color palette usage across several components to improve visual consistency and accessibility. The main change is replacing the use of `neutral-50` with `neutral-60` for disabled and placeholder states in various UI elements. 
Additionally, some unnecessary explicit color settings have been removed from certain components.
**Theme color updates:**
* Updated disabled and placeholder text color from `neutral-50` to `neutral-60` in `Breadcrumb`, `Link`, `Tabs`, and default field themes for better contrast and consistency. [[1]](diffhunk://#diff-ec90dbeba0a7f574471730f692870dbb526b14479f2b572082f12e201136256aL24-R24) [[2]](diffhunk://#diff-ed7d085ea112453cd7ebd3779184379d26427bbde9309fe7702fe00f3cea4942L30-R30) …

Fix: use a contrast compliant color for texts

---

lib/tsconfig.json
lib/vite.config.mjs

TLDR:
`@*` doesn't work 😎 
**Configuration improvements:**
* Updated the `@` path alias in `tsconfig.json` from `"@*": ["./src/*"]` to `"@/*": ["./src/*"]` for clearer and more accurate path mapping.
* Changed the Vite alias from `'@*': path.resolve(__dirname, './src')` to `'@': path.resolve(__dirname, './src')`, and removed the redundant `'@/utils'` alias, simplifying and standardizing how imports from `src` are handled.

chore: update aliases config

---

lib/src/components/Button/button.module.scss
lib/src/components/Button/docs/properties.json
lib/src/components/Button/index.tsx
lib/src/components/Button/types.ts
lib/src/components/ButtonGroup/button-group.module.scss
lib/src/components/ButtonGroup/docs/examples/overload.tsx
lib/src/components/ButtonGroup/docs/examples/overview.tsx
lib/src/components/ButtonGroup/docs/index.mdx
lib/src/components/ButtonGroup/docs/properties.json
lib/src/components/ButtonGroup/index.test.tsx
lib/src/components/ButtonGroup/index.tsx
lib/src/components/ButtonGroup/types.ts
website/build-app/examples.js

This pull request introduces a new `ButtonGroup` component, complete with styling, documentation, type definitions, and example usage. It also makes minor improvements to the existing `Button` component's styles to support better integration with `ButtonGroup`. The update ensures that grouped buttons are visually cohesive and that shared props like `size`, `variant`, and `disabled` are consistently applied.
**ButtonGroup Component Addition:**
* Added the new `ButtonGroup` component in `index.tsx`, which wraps multiple `Button` components, propagates shared props (`size`, `variant`, `disabled`), and applies group-specific styles.
* Introduced SCSS module `button-group.module.scss` to handle layout, spacing, and border-radius adjustments for grouped buttons.
* Defined types for …

[WUI-211] Chore: migrate button group

---

lib/src/components/InputText/docs/examples/clearable.tsx
lib/src/components/InputText/docs/examples/disabled.tsx
lib/src/components/InputText/docs/examples/icon.tsx
lib/src/components/InputText/docs/examples/overview.tsx
lib/src/components/InputText/docs/examples/sizes.tsx
lib/src/components/InputText/docs/examples/transparent.tsx
lib/src/components/InputText/docs/examples/variants.tsx
lib/src/components/InputText/docs/index.mdx
lib/src/components/InputText/docs/properties.json
lib/src/components/InputText/index.tsx
lib/src/components/InputText/input-text.module.scss
lib/src/components/InputText/tests/index.test.tsx
lib/src/components/InputText/types.ts
website/app/global.css
website/build-app/examples.js

This pull request introduces a new `InputText` component to the codebase, complete with implementation, documentation, examples, styles, type definitions, and tests. It also integrates the component into the website's global styles and example loader, ensuring it is available for documentation and demonstration purposes.
**New InputText Component Implementation and Integration**
* Added the `InputText` component in `lib/src/components/InputText/index.tsx`, supporting custom variant and sizes. And with disabled, focused and hover states.
* Defined prop types and options for `InputText` in `lib/src/components/InputText/types.ts`, including support for custom size and variant.
* Created comprehensive SCSS styles for the `InputText` component, including size variants and icon positioning, in …

chore: migrate input text to tailwind

---

lib/src/components/Textarea/docs/examples/overview.tsx
lib/src/components/Textarea/docs/examples/variants.tsx
lib/src/components/Textarea/docs/index.mdx
lib/src/components/Textarea/docs/properties.json
lib/src/components/Textarea/index.tsx
lib/src/components/Textarea/tests/index.test.tsx
lib/src/components/Textarea/textarea.module.scss
lib/src/components/Textarea/types.ts
website/app/global.css
website/build-app/examples.js

This pull request introduces a new `Textarea` component to the codebase, complete with implementation, documentation, examples, styles, type definitions, and tests. It also integrates the component into the website's global styles and example loader, ensuring it is available for documentation and demonstration purposes.
**New Textarea Component Implementation and Integration**
* Added the `Textarea` component in `lib/src/components/Textarea/index.tsx`, supporting custom variant and sizes. And with disabled, focused and hover states.
* Defined prop types and options for `Textarea` in `lib/src/components/Textarea/types.ts`, including support for custom size and variant.
* Created comprehensive SCSS styles for the `Textarea` component, including size variants and icon positioning, in …

chore: migrate textarea to tailwind

---

lib/src/components/Button/docs/index.mdx
lib/src/components/Button/docs/properties.json
lib/src/components/Button/index.test.tsx
lib/src/components/Button/index.tsx
lib/src/components/Button/types.ts
lib/src/components/ButtonGroup/index.test.tsx
lib/src/components/ButtonGroup/index.tsx
lib/src/utils/forwardRefWithAs.tsx
lib/tests/index.tsx

This pull request introduces polymorphic `as` prop support to the `Button` and `ButtonGroup` components, allowing them to render as different HTML elements or custom components. It achieves this by adding a new utility, `forwardRefWithAs`, and refactoring component and type definitions accordingly. The changes also update tests and documentation to reflect the new polymorphic capabilities.
**Polymorphism and Refactoring:**
* Added `forwardRefWithAs` utility to enable polymorphic `as` prop support and ref forwarding for components. (`lib/src/utils/forwardRefWithAs.tsx`)
* Refactored `Button` and `ButtonGroup` components to use `forwardRefWithAs`, supporting the `as` prop and updating their display names. (`lib/src/components/Button/index.tsx`, `lib/src/components/ButtonGroup/index.tsx`) …

[WUI-213] Chore: add forwardRefWithAs to handle polymorphism

---

lib/src/components/Avatar/avatar.module.scss
lib/src/components/Avatar/docs/examples/images.tsx
lib/src/components/Avatar/docs/examples/overview.tsx
lib/src/components/Avatar/docs/examples/sizes.tsx
lib/src/components/Avatar/docs/examples/texts.tsx
lib/src/components/Avatar/docs/index.mdx
lib/src/components/Avatar/docs/properties.json
lib/src/components/Avatar/index.tsx
lib/src/components/Avatar/tests/index.test.tsx
lib/src/components/Avatar/tests/utils.test.ts
lib/src/components/Avatar/types.ts
lib/src/components/Avatar/utils.ts
website/build-app/examples.js

Breaking changes:
- No more `color` prop. Override color using Tailwind instead (e.g. `<Avatar className="bg-brand-40" />`)
- No more `w` or `h` prop. Override size using Tailwind `size` (e.g. `<Avatar className="size-[100px]" />`)

chore: migrate the Avatar component to be tailwind-compatible

---

scripts/upgrade-v9.mjs
website/app/blog/page.tsx
website/build-app/components/Homepage/Components.tsx
website/build-app/components/Mdx/Playground.tsx

Fixed script migration for Stack 🙈
- if no direction we put `flex-col` (column is default on old Stack component)
- remove unnecessary `flex-row`

ci: fix migration script for Stack

---

lib/src/components/Modal/Assets/assets.module.scss

This pull request imports breakpoint variables from the shared theme utilities.
**SCSS breakpoints refactor:**
* Imported the `breakpoints` module from the shared theme utilities for consistent breakpoint values.
* Replaced hardcoded pixel values (`736px` and `1700px`) in media queries with `breakpoints.$breakpoint-md` and `breakpoints.$breakpoint-3xl` variables throughout the file, ensuring easier updates and alignment with design system standards. [[1]](diffhunk://#diff-6fe9417db25e2b791fc755a9493b9507a9e54bd3da469701f249c170583174f2R1-R12) [[2]](diffhunk://#diff-6fe9417db25e2b791fc755a9493b9507a9e54bd3da469701f249c170583174f2L77-R78) [[3]](diffhunk://#diff-6fe9417db25e2b791fc755a9493b9507a9e54bd3da469701f249c170583174f2L90-R90) …

Chore: use breakpoint utils for breakpoint declarations

---

lib/src/components/Search/docs/examples/option-groups.tsx
lib/src/components/Search/docs/examples/overview.tsx
lib/src/components/Search/docs/index.mdx
lib/src/components/Search/docs/properties.json
lib/src/components/Search/index.test.tsx
lib/src/components/Search/index.tsx
lib/src/components/Search/search.module.scss
lib/src/components/Search/types.ts
lib/src/components/Select/docs/properties.json
lib/src/components/Select/index.tsx
lib/src/components/Select/select.module.scss
lib/src/utils/throttle.ts
website/build-app/examples.js

This PR migrates Search to tailwind
**A few thing changed**
- Search is always clearable so i removed the prop and simplified the css of icon placement and spacing
- we were not reading and using props `transparent`
It also fixes icon placement right for the Select
- Overall icon placements with the clear button and the dropdown indicator is not optimal 
- Search & Select should be reworked in that aspect with InputText as a blueprint

Chore: migrate Search component to tailwind [WUI-172]
